type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Note @table {
  user: User!
  title: String!
  content: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  isFavorite: Boolean
}

type Tag @table {
  user: User!
  name: String!
  createdAt: Timestamp!
}

type NoteTag @table(key: ["note", "tag"]) {
  note: Note!
  tag: Tag!
  createdAt: Timestamp!
}